### ISSUE TITLE
Question:Possibility of adding a temporal component to the clustering

### ISSUE THREAD

**Issue by Emmanuel-Mekonnen** [nla-group/classix#10]
I wanted to know if it's possible to add a temporal component when it comes to how each node is clustered. Nodes with a close timestamp are clustered and this would take precedence over the spatial.

**Comment by guettel** [comment]
Hi Emmanuel, thanks for your interest and question! 

If your data has n features, you could add the temporal coordinate as the (n+1) feature. For example if your data matrix `X` is 10x4 (10 data points with 4 features) and you have vector `t` of 10 time stamps, do:

```
import numpy as np
X = np.random.rand(10, 4) # 10 data points with 4 features
t = np.random.rand(10, 1) # 10 time stamps
s = 1                     # scaling
Xt = np.c_[X, s*t]
# now cluster Xt
```

Depending on the scaling parameter `s`, you can give more or less weight to the temporal direction.
