### ISSUE TITLE
Error will be reported when the feature dimension is greater than 3

### ISSUE THREAD

**Issue by MotorZ** [nla-group/classix#11]
Hi, Xinye!
Thank you for your excellent work!
I try to apply your method to my own multi-dim dataset. I found if the 'n_features' > 3 will lead to an error(also will perform on the synthetic dataset ):

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_8868\670907302.py in <module>
      7 # Call CLASSIX
      8 clx = CLASSIX(radius=0.5, verbose=0)
----> 9 clx.fit(X)

E:\Anaconda3\envs\DL-main\lib\site-packages\classix\clustering.py in fit(self, data)
    488 
    489         # aggregation
--> 490         self.groups_, self.splist_, self.dist_nr = self.aggregate(data=self.data, sorting=self.sorting, tol=self.radius)
    491         self.splist_ = np.array(self.splist_)
    492 

E:\Anaconda3\envs\DL-main\lib\site-packages\classix\aggregation.py in aggregate(data, sorting, tol)
     82                 sort_vals = data@U1.reshape(-1)
     83             else:
---> 84                 U1, s1, _ = svds(data, k=1, return_singular_vectors="u")
     85                 sort_vals = U1[:,0]*s1[0]
     86 

**NameError: name 'svds' is not defined**
____________________________________________________________________________
from sklearn import datasets
from classix import CLASSIX

# Generate synthetic data
X, y = datasets.make_blobs(n_samples=5000, centers=2, **n_features**=25, random_state=1)

# Call CLASSIX
clx = CLASSIX(radius=0.5, verbose=0)
clx.fit(X)
_____________________________________________________________________________
Maybe I use your method in a wrong way. Could you tell me  how to get CLASSIX work on muiti-dim data?
Any advise will be thankful!
Best wishes!

**Comment by chenxinye** [comment]
Hi @MotorZ

Thanks for your interest! I guess you are using the old version, please update it to the latest version. 

To obtain faster clustering, you can use Cython installation. To check if Cython is installed, please use:

```
import classix

classix.cython_is_available()
```

We recommend you read the document for further detail.


Best,
Xinye

**Comment by MotorZ** [comment]
Thank you very much for your patience, indeed the problem was solved after I updated the version! Thank you again for your impressive work!
 
Best wishes!
