### ISSUE TITLE
Access of timing information

### ISSUE THREAD

**Issue by guettel** [nla-group/classix#15]
It would be useful to have some way to access runtimes of the individual parts of CLASSIX after the clustering is computed. Largely, I think there are essentially five components:

- t1_prepare: The initial data preparation, which mainly comprises data scaling and the computation of the first two principal axes.
- t2_aggregate: This phase aggregates all data points into groups determined by the radius parameter of CLASSIX.
- t3_merge: The computed groups will be merged into clusters when their group centers (starting points) are sufficiently close.
- t4_minPts: Clusters with fewer than minPts points will be dissolved into their groups, and each of the groups will then be reassigned to a large enough cluster.
- t5_finalize: Any cleanup activities. 

See also the MATLAB version:
https://github.com/nla-group/classix-matlab/blob/main/demos/The_out_structure_returned_by_CLASSIX.md

**Comment by chenxinye** [comment]
A new branch is opened for this enhancement. After testing, will be formally merged into main branch.

**Comment by chenxinye** [comment]
The timing information can be accessed via the method: 
> ``clx.timing()``
