### ISSUE TITLE
Avoid recomputation of PCA and distance computations in .explain()

### ISSUE THREAD

**Issue by guettel** [nla-group/classix#19]
The current implementation of .explain() performs superfluous computations which could be avoided:

(i) Currently, every call to .explain() computes the two leading principal components of the data. This should be done only once when .fit(data) is called. For CLASSIX itself only the first PCA is needed, but there is no harm getting the second component as well and storing it for .explain().

(ii) The current .explain(ind1,ind2) method computes a shortest path between the group centres, recomputing all the distances between them. This is unnecessary and can become very slow, especially for clusters with many points (e.g. in image segmentation). The distances between overlapping groups have already been computed in the merging phase, and all that is needed is the adjacency matrix of overlapping groups. 

Both of these optimizations are implemented in the MATLAB code 
https://github.com/nla-group/classix-matlab/blob/main/classix.m

**Comment by chenxinye** [comment]
Resolve this issue by adding new feature in explain method. This feature enables consecutive distances track, in which distance computation is necessary in the explain.

**Comment by chenxinye** [comment]
These
