### ISSUE TITLE
Allow indexing with data frame labels

### ISSUE THREAD

**Issue by guettel** [nla-group/classix#5]
Assume I have a date frame `df` like
```
Anna   0.3   -0.1   0.5
Bert   0.0   -0.2   0.7
Carl  -0.8   -0.1   0.2
```
where the first column is the index. It would be nice to be able to do 
```
clx = CLASSIX(radius=0.5)
clx.fit(df)
clx.explain('Anna', 'Bert')
```
and get an output similar to 
```
The data point 'Anna' is in group 0, which has been merged into cluster 0.
The data point 'Bert' is in group 1, which has been merged into cluster 1.
There is no path of overlapping groups between these clusters.
```

The table of groups could contain an additional column for the label:
```
-------------------------------------------------
 Group  Label   NrPts  Cluster  Coordinates  
   0    'Anna'  1      0        0.3   -0.1   0.5
   1    'Bert'  2      1        0.0   -0.2   0.7
-------------------------------------------------
```

The plot function could also use the labels instead of numerical point indices, but there should probably be an option to revert to numerical indices for the starting points if they plot gets too cluttered.

**Comment by chenxinye** [comment]
Update it to version 0.5.5 now!
