### ISSUE TITLE
Fail instalment

### ISSUE THREAD

**Issue by chenxinye** [nla-group/classix#7]
Some users cannot install CLASSIX by `pip install classix` and report the installing issue. I told them classix is also another software name. Instead we should use `pip install ClassixClustering`.

**Comment by guettel** [comment]
This could also have to do with the name of the module "classix" when
reading the code.

I propose we change the module name to ClassixClustering as well. So that
the syntax becomes

from ClassixClustering import classix

But only after we get the reviews for the paper.
