### ISSUE TITLE
group_merging=='none'

### ISSUE THREAD

**Issue by guettel** [nla-group/classix#8]
It would be helpful and intuitive to return the group labels as obtained by the aggregation phase when

`group_merging.lower()=='none' or group_merging is None `

In this case the cluster labels are just the group labels returned by aggregation.

**Comment by chenxinye** [comment]
Dear users,

Stefan and I just submitted the new version of classix. Now we have added a new feature for CLASSIX, please refer to the release information for detail. 

Thanks,
Xinye
